#!/usr/bin/env bash
#
# Render /etc/samba/smb.conf from the template plus every share fragment.
#
# Samba expands `%U` in an `include =` only once a session is already
# authenticated, so a per-user include never reaches share enumeration:
# the shares are invisible to `testparm`, to Finder's share list and to
# the Time Machine picker. Instead we inline the fragments here and
# re-render whenever the share set changes.
#
# Usage:
#   render-smb-conf.sh [--no-reload]
#
# Called by entrypoint-samba.sh at start and by create-user.sh /
# delete-user.sh after they add or remove a fragment.

set -euo pipefail

TEMPLATE="${TEMPLATE:-/etc/timenest/smb.conf.template}"
SHARES_DIR="${SHARES_DIR:-/etc/timenest/shares.d}"
TARGET="${TARGET:-/etc/samba/smb.conf}"

RELOAD=yes
if [[ "${1:-}" == "--no-reload" ]]; then
    RELOAD=no
fi

log() { printf '[render-smb-conf] %s\n' "$*"; }
die() { printf '[render-smb-conf] ERROR: %s\n' "$*" >&2; exit 1; }

# ---------------------------------------------------------------------------
# Env defaults and derived values. Duplicated nowhere else: the entrypoint
# calls this script rather than rendering inline, and `docker exec` hands
# the container environment to create-user.sh / delete-user.sh too.
# ---------------------------------------------------------------------------
: "${SERVER_NAME:=TimeNest}"
: "${DEVICE_MODEL:=TimeCapsule8,119}"
: "${SMB_INTERFACES:=}"
: "${LOG_LEVEL:=INFO}"

case "${LOG_LEVEL^^}" in
    DEBUG)   SAMBA_LOG_LEVEL=3 ;;
    ERROR)   SAMBA_LOG_LEVEL=0 ;;
    *)       SAMBA_LOG_LEVEL=1 ;;
esac

# `bind interfaces only` makes sense only when interfaces are given.
if [[ -n "$SMB_INTERFACES" ]]; then
    BIND_INTERFACES_ONLY=yes
else
    BIND_INTERFACES_ONLY=no
    SMB_INTERFACES=""
fi

export SERVER_NAME DEVICE_MODEL SMB_INTERFACES BIND_INTERFACES_ONLY SAMBA_LOG_LEVEL

[[ -r "$TEMPLATE" ]] || die "template not found: ${TEMPLATE}"
mkdir -p "$SHARES_DIR" "$(dirname "$TARGET")"

# ---------------------------------------------------------------------------
# Build into a temp file next to the target so the final move is atomic and
# a broken fragment can never leave smbd with a half-written config.
# ---------------------------------------------------------------------------
TMP="$(mktemp "${TARGET}.XXXXXX")"
trap 'rm -f "$TMP"' EXIT

# The template uses ${VAR} syntax - envsubst only replaces explicitly
# listed vars to avoid accidentally eating literal `$` in comments.
# shellcheck disable=SC2016  # single quotes intentional; envsubst reads literal ${VAR} list
envsubst '${SERVER_NAME} ${DEVICE_MODEL} ${SMB_INTERFACES} ${BIND_INTERFACES_ONLY} ${SAMBA_LOG_LEVEL}' \
    < "$TEMPLATE" > "$TMP"

# LC_ALL=C keeps the order locale-independent, so the rendered file stays
# diffable between runs and between hosts.
FRAGMENTS=()
mapfile -t FRAGMENTS < <(find "$SHARES_DIR" -maxdepth 1 -type f -name '*.conf' | LC_ALL=C sort)

{
    printf '\n'
    printf '# --- share fragments inlined from %s ---\n' "$SHARES_DIR"
    printf '# Generated by render-smb-conf.sh. Edit the fragments, not this file.\n'
} >> "$TMP"

for frag in "${FRAGMENTS[@]+"${FRAGMENTS[@]}"}"; do
    {
        printf '\n# >>> %s\n' "$frag"
        cat "$frag"
    } >> "$TMP"
done

if (( ${#FRAGMENTS[@]} == 0 )); then
    printf '# (no shares configured yet)\n' >> "$TMP"
fi

# ---------------------------------------------------------------------------
# Validate before publishing. A bad fragment keeps the previous config live.
# ---------------------------------------------------------------------------
if ! testparm -s "$TMP" > /dev/null 2>&1; then
    log "testparm output:"
    testparm -s "$TMP" || true
    die "rendered config failed to parse; keeping the existing ${TARGET}"
fi

chmod 0644 "$TMP"
mv -f "$TMP" "$TARGET"
trap - EXIT
log "rendered ${TARGET} with ${#FRAGMENTS[@]} share(s)"

if [[ "$RELOAD" == yes ]] && pidof smbd >/dev/null; then
    log "reloading smbd"
    pkill -HUP smbd || true
fi
